version: 0.2

phases:

  build:
    commands:
      - chown -R florian:florian .
#      - su florian -c "source /synopsys/scripts/env.sh; echo $PATH"
# VCS environment
      - export VCS_HOME=/synopsys/vcs/S-2021.09-SP1
      - export PATH=$VCS_HOME/bin:$PATH
      - vcs -id
# Questasim (vsim) environment
#      - export QUESTAROOT=/onespin/questasim
#      - export LM_LICENSE_FILE=29000@ip-172-31-46-244
#      - export PATH=${QUESTAROOT}/bin:${PATH}
#      - export MTI_VCO_MODE=64
#      - wget https://buildbot.embecosm.com/job/corev-gcc-centos7/19/artifact/corev-openhw-gcc-centos7-20230905.tar.gz
      - curl -O https://buildbot.embecosm.com/job/corev-gcc-centos7/19/artifact/corev-openhw-gcc-centos7-20230905.tar.gz
      - tar xf corev-openhw-gcc-centos7-20230905.tar.gz
      - export CV_SW_TOOLCHAIN=corev-openhw-gcc-centos7-20230905
      - export CV_SW_PREFIX=riscv32-corev-elf-
      - export CV_SW_MARCH=rv32imc_zicsr_zifencei
      - corev-openhw-gcc-centos7-20230905/bin/riscv32-corev-elf-gcc --version
      - cd cv32e40p/sim/uvmt
#      - make test USE_ISS=0 SIMULATOR=vcs TEST=hello-world
